version: 2.17.2
services:
  adminer:
    container_name: Adminer     # Name redirect to IP -> 172.X.X.Z
    hostname: root
    build: adminer/.  # Build the dockerfile in ./adminer_directory/Dockerfile 
    restart: always             # Restart the container if it has stopped
    ports:
      - "80:80"                 # Redirect port 80 of Adminer on the host
    networks:
      - inception   

  nginx:
    container_name: nginx
    hostname: root
    build: ./nginx/ 
    image: nginx:aweaver
    env_file: 
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/wordpress
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    hostname: root
    build: ./mariadb/
    image: mariadb:aweaver
    env_file: 
      - .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysql", "-u", "${DATABASE_LOGIN}", "-p${DATABASE_PASSWORD}"]
      interval: 30s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    hostname: root
    build:  
      context: ./wordpress/
    image: wordpress:aweaver
    env_file: 
      - .env
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress-data:/var/www/html/wordpress
    restart:  on-failure
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/aweaver/data/mariadb-data
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/aweaver/data/wordpress-data

networks:
  inception:
    driver: bridge
