services:
  nginx:
    build:  /nginx/Dockerfile
    ports:  "443:443"
    restart:  on_failure

  mariadb:
    build:  /nginx/Dockerfile
    volumes: mariadb_data:/data/db
    restart: on_failure
    depends_on: nginx

  wordpress:
    build:  /nginx/Dockerfile
    volumes:  wordpress_data:/data/wordpress
    restart:  on_failure
    depends_on:
      - nginx
      - mariadb
