services:
  nginx:
    container_name: nginx
    build: ./nginx/ 
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress-data:/home/aweaver/data/wordpress

  mariadb:
    container_name: mariadb
    build: ./mariadb/
    env_file: .env
    volumes:
      - mariadb-data:/home/aweaver/data/mariadb
    restart: on-failure
    depends_on:
      - nginx

  wordpress:
    container_name: wordpress
    build:  ./wordpress/
    env_file: .env
    volumes:
      - wordpress-data:/home/aweaver/data/wordpress
    restart:  on-failure
    depends_on:
      - mariadb

volumes:
  mariadb-data:
  wordpress-data:
