services:
  nginx:
    container_name: nginx
    build: ./nginx/ 
    image: nginx
    env_file: 
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
    volumes:
      - wordpress-data:/var/www/html/wordpress

  mariadb:
    container_name: mariadb
    build: ./mariadb/
    image: mariadb
    env_file: 
      - .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: on-failure
    depends_on:
      - nginx

  wordpress:
    container_name: wordpress
    build:  
      context: ./wordpress/
    image: wordpress
    env_file: 
      - .env
    networks:
      - inception
    expose:
      - "9000"
    volumes:
      - wordpress-data:/var/www/html/wordpress
    restart:  on-failure
    depends_on:
      - mariadb

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/aweaver/data/mariadb-data
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/aweaver/data/wordpress-data
  nginx-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/aweaver/data/wordpress-data

networks:
  inception:
    driver: bridge
